# Vectors and Matrices

In [57]:
a = [1,2,3]

# num elements:
size(a)

# num dimensions, 1-dim is "flat
ndims(a)

# identity matrix, matrix = 2-dim vector
eye(3)

# spaces indicate columns, e.g. 1x3 row vector
a = [1 2 3]

# flatten
squeeze(a, 1)

# must transpose to create column vector
a = [1 2 3]'

# 2x2: ';' is row break
a = [1 2; 3 4]

# indexing is straightforward
# first row
a[1, :]

# first col
a[:, 1]

# use booleans to get cell values
a = randn(2, 2)
b = [true; false; false; true]
a[b]

# arrays passed by reference
a = [1, 2, 3]
b = a
b[2] = 3
a # [1, 3, 3]

# use copy to make copy
b = copy(a)
b[2] = 2
a # differs from b

# standard methods on arrays
sum(a)
std(a)
var(a)
maximum(a)
minimum(a)

# new (to me) methods
a = [5, 1, 8]

# index of max
indmax(a)

# sorted (in reverse, optional) indices
sortperm(a, rev=true) 

3-element Array{Int64,1}:
 3
 1
 2

# Linear Algebra

In [1]:
a = [1 2]
b = [2 2; 3 1]

# matrix mulitplication
a * b

# element-wise (broadcasting, in this case) multiplication
a .* b

# outer product
a = [2; 3]
b = [2 2]
a * b

# solve Ax = b
A = [1 2; 3 1]
b = [1; 3]

A \ b     # [1 0]'
A * [1 0]' # b


# dot product
dot(ones(2), ones(2))

# Element-wise
i = [2 2]
j = [3 4]
i .* j

# Comparisons
a = [1, 2, 3]
b = [2, 1, 3]

a .> b

3-element BitArray{1}:
 false
  true
 false

search: norm normpath normalize normalize! normalize_string vecnorm issubnormal



```
norm(A::AbstractArray, p::Real=2)
```

Compute the `p`-norm of a vector or the operator norm of a matrix `A`, defaulting to the 2-norm.

```
norm(A::AbstractVector, p::Real=2)
```

For vectors, this is equivalent to [`vecnorm`](@ref) and equal to:

$$
\|A\|_p = \left( \sum_{i=1}^n | a_i | ^p \right)^{1/p}
$$

with $a_i$ the entries of $A$ and $n$ its length.

`p` can assume any numeric value (even though not all values produce a mathematically valid vector norm). In particular, `norm(A, Inf)` returns the largest value in `abs(A)`, whereas `norm(A, -Inf)` returns the smallest.

# Example

```jldoctest
julia> v = [3, -2, 6]
3-element Array{Int64,1}:
  3
 -2
  6

julia> norm(v)
7.0

julia> norm(v, Inf)
6.0
```

```
norm(A::AbstractMatrix, p::Real=2)
```

For matrices, the matrix norm induced by the vector `p`-norm is used, where valid values of `p` are `1`, `2`, or `Inf`. (Note that for sparse matrices, `p=2` is currently not implemented.) Use [`vecnorm`](@ref) to compute the Frobenius norm.

When `p=1`, the matrix norm is the maximum absolute column sum of `A`:

$$
\|A\|_1 = \max_{1 ≤ j ≤ n} \sum_{i=1}^m | a_{ij} |
$$

with $a_{ij}$ the entries of $A$, and $m$ and $n$ its dimensions.

When `p=2`, the matrix norm is the spectral norm, equal to the largest singular value of `A`.

When `p=Inf`, the matrix norm is the maximum absolute row sum of `A`:

$$
\|A\|_\infty = \max_{1 ≤ i ≤ m} \sum _{j=1}^n | a_{ij} |
$$

# Example

```jldoctest
julia> A = [1 -2 -3; 2 3 -1]
2×3 Array{Int64,2}:
 1  -2  -3
 2   3  -1

julia> norm(A, Inf)
6.0
```

```
norm(x::Number, p::Real=2)
```

For numbers, return $\left( |x|^p \right)^{1/p}$. This is equivalent to [`vecnorm`](@ref).

```
norm(A::RowVector, q::Real=2)
```

For row vectors, return the $q$-norm of `A`, which is equivalent to the p-norm with value `p = q/(q-1)`. They coincide at `p = q = 2`.

The difference in norm between a vector space and its dual arises to preserve the relationship between duality and the inner product, and the result is consistent with the p-norm of `1 × n` matrix.


# Exercises

## Exercise 1

In [38]:
function solve_lyapunov(A, Σ, n_iter=200)
    seq = [eye(size(A)[1])]
    for i in 1:n_iter-1
        S_t = seq[end]
        push!(seq, A * S_t * A' + Σ * Σ')
    end
    return seq
end

A, Σ = [0.8 -0.2; -0.1 0.7], [0.5 0.4; 0.4 0.6]
S = solve_lyapunov(A, Σ)[end]
A * S * A' + Σ * Σ'

2×2 Array{Float64,2}:
 0.671231  0.633474
 0.633474  0.858874

## Practice Simulation

1×19 RowVector{Float64,Array{Float64,1}}:
 1.0  1.5  2.0  2.5  3.0  3.5  4.0  …  7.0  7.5  8.0  8.5  9.0  9.5  10.0

In [17]:
X = collect(1:.5:10)'
y = 2 + 0.4 * X + randn(size(x));

LoadError: DimensionMismatch("dimensions must match")